### PR TITLE
remove deprecated option

### PR DESCRIPTION
**Pull request by smiller171**

### CODE REVIEW

**Comment by smiller171** [comment]
looks like there's a bunch of deprecations. Working on them.

**Comment by keithamus** [comment]
Yeah @smiller171 this config is very undermaintained. If you would like I can grant you maintainership of this repository.

**Comment by smiller171** [comment]
@keithamus Are you aware of a better maintained repo that accomplishes this? If so it would likely be better to just archive this repo.

**Comment by keithamus** [comment]
@smiller171 sadly no - it has been a few years since I last used stylelint. I'm hesitant to archive, because I dont just want to squat the name; if someone could pick up the maintainence duties then this could be a useful package again!

**Comment by smiller171** [comment]
I'm hesitant to take it myself because I don't have a great history of maintaining these things, and so far I haven't gotten stylelint to work for me at all.

**Comment by keithamus** [comment]
That's totally cool; if you want I'll let this PR sit here and if you ever feel like you want to pick up maintainence just drop me a comment here and I'll give you the keys 😉

**Comment by smiller171** [comment]
@keithamus This PR is ready to merge if you want to bring things up to date for now. The test that's still failing is stuff you did. Your tab length in your examples doesn't match what you're testing for.

**Comment by keithamus** [comment]
👍 if I get any time to fix the tests I'll do so.

**Pull request merged**
